### ISSUE TITLE
Command with arguments in-between subcommands throws NPE

### ISSUE THREAD

**Issue by knightzmc** [Incendo/cloud#106]
The command:
```kotlin
@CommandMethod("boosters type <identifier> canstack <value>")
fun boosterCanStack(sender: CommandSender, @Argument("identifier") identifier: String, @Argument("value") canStack: Boolean)
```
being called with `/boosters type test canstack false`

fails with a NullPointerException:
```
11:42:23 WARN]: java.lang.NullPointerException: No such object stored in the context: identifier
[11:42:23 WARN]:        at cloud.commandframework.context.CommandContext.get(CommandContext.java:190)
[11:42:23 WARN]:        at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:69)
[11:42:23 WARN]:        at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$0(AsynchronousCommandExecutionCoordinator.java:82)
[11:42:23 WARN]:        at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$2(AsynchronousCommandExecutionCoordinator.java:109)
[11:42:23 WARN]:        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
[11:42:23 WARN]:        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
[11:42:23 WARN]:        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
[11:42:23 WARN]:        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
[11:42:23 WARN]:        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
```

despite the fact that `test` is being passed for `identifier`

Presumably a bug in annotation parsing, but I'm not familiar enough with the codebase to tell.

**Comment by jmanpenilla** [comment]
Based on our Discord conversation, this is due to having another command registered which made your commands ambiguous.
```
booster type info <identifier>
booster type <identifier> rewards 
```
and we recommended to use a structure like
```
booster type <identifier> info|rewards
```
A future update of cloud (1.2.0) will attempt to avoid confusion around these types of ambiguous cases by detecting them during verification of the command tree, instead of allowing them to be registered which leads to broken behavior (as is "intended" due to the unsupported nature).
