### ISSUE TITLE
Improve toString() of classes that stringify TypeToken

### ISSUE THREAD

**Issue by bergerkiller** [Incendo/cloud#217]
There are some cases where the object responsible for something in cloud reports an error, where that object is printed. One such class is ServiceWrapper, which sadly does a TypeToken.toString(), which isn't implemented. This results in garbage being printed that is useless for a developer trying to fix such issues.

For example:
```
[17:31:16] [Server thread/ERROR]: [Train_Carts] Exception executing command handler
com.bergerkiller.bukkit.tc.dep.cloud.services.PipelineException: Failed to retrieve result from 
ServiceWrapper{
   type=com.bergerkiller.bukkit.tc.dep.cloud.annotations.injection.ParameterInjectorRegistry$1@c51fe3c,
   implementation=com.bergerkiller.bukkit.tc.dep.typetoken.TypeToken$1@294e3e87
 }
	at com.bergerkiller.bukkit.tc.dep.cloud.services.ServiceSpigot.getResult(ServiceSpigot.java:98) ~[?:?]
	at com.bergerkiller.bukkit.tc.dep.cloud.annotations.injection.ParameterInjectorRegistry.getInjectable(ParameterInjectorRegistry.java:136) ~[?:?]
	at com.bergerkiller.bukkit.tc.dep.cloud.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:92) ~[?:?]
	at com.bergerkiller.bukkit.tc.dep.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
```

Code should be reviewed and any place where TypeToken.toString() is used, a suitable alternative is chosen.

I kinda don't know how to fix the example error right now, because I have no clue what object is involved or even what 'injector handler' is responsible. And it doesn't lead into any of my own code either :/

**Comment by Citymonstret** [comment]
For reference: https://github.com/Incendo/cloud/blob/master/cloud-services/src/main/java/cloud/commandframework/services/ServiceRepository.java#L140

**Comment by jpenilla** [comment]
Use of TypeToken#toString should be replaced, see https://github.com/Incendo/cloud/commit/f7e756e901b8217b516511a8ca700b5a1c62cfb1

**Comment by jpenilla** [comment]
https://github.com/Incendo/cloud/commit/dc00a3a4f63c5d1e49359d0c13965fe2728969eb
