### ISSUE TITLE
Unable to register commands as expected

### ISSUE THREAD

**Issue by book000** [Incendo/cloud#244]
Thank you for creating a great framework. I'm using this framework to create PaperMC plugin commands.
I'm sorry for the consecutive days of posting.

I would like to implement a command the following:

- `/teleport <warpName>`: Teleports the player who executed the command to the specified location.
- `/teleport <player> <warpName>`: Teleports the specified player to the specified location.

To implement this, I wrote the following code (These are in `onEnable`):

```java
final PaperCommandManager<CommandSender> manager;
try {
    manager = new PaperCommandManager<>(this, CommandExecutionCoordinator.SimpleCoordinator.simpleCoordinator(),
            Function.identity(), Function.identity());
} catch (Exception e) {
    e.printStackTrace();
    return;
}
Command.Builder<CommandSender> builder = manager.commandBuilder("teleport");
manager.command(builder
        .senderType(Player.class)
        .argument(StringArgument
            .<CommandSender>newBuilder("warpName")
            .withSuggestionsProvider(this::suggestWarpNames))
        .handler(this::teleport)
        .build());

manager.command(builder
    .argument(MultiplePlayerSelectorArgument
        .newBuilder("player"))
    .argument(StringArgument
        .<CommandSender>newBuilder("warpName")
        .withSuggestionsProvider(this::suggestWarpNames))
    .handler(this::teleport)
    .build());
```

However, when I run it, it shows an error when starting the server.

```
[18:42:09] [Server thread/ERROR]: Error occurred while enabling PLUGIN v0.0.1 (Is it up to date?)
cloud.commandframework.exceptions.AmbiguousNodeException: Ambiguous Node: warpName cannot be added as a child to teleport (All children: warpName, player)
	at cloud.commandframework.CommandTree.checkAmbiguity(CommandTree.java:833) ~[?:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:1.8.0_281]
	at cloud.commandframework.CommandTree.checkAmbiguity(CommandTree.java:864) ~[?:?]
	at cloud.commandframework.CommandTree.verifyAndRegister(CommandTree.java:760) ~[?:?]
	at cloud.commandframework.CommandTree.insertCommand(CommandTree.java:705) ~[?:?]
	at cloud.commandframework.CommandManager.command(CommandManager.java:227) ~[?:?]
	at com.tomacheese.plugin.Main.onEnable(Main.java:66) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-547]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-547]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-547]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-547]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-547]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:468) ~[patched_1.16.5.jar:git-Paper-547]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:241) ~[patched_1.16.5.jar:git-Paper-547]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:943) ~[patched_1.16.5.jar:git-Paper-547]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.5.jar:git-Paper-547]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
```

What can I do to fix this?
Sorry for the poor English. I look forward to your reply.

**Comment by broccolai** [comment]
Don't worry about making new issues and your English is good!

This is a limitation with cloud and how it structures it's tree. For us it's impossible to know whether we should be parsing a <player> or a <warpName>.

To work around it you could move the player after the warpname or make your own Warp argument that can parse either.

Let us know if you have any more questions ^^

**Comment by book000** [comment]
Thanks for your quick reply.

In that case, it is a little off the main topic of the Issue, but is it possible to parse selectors such as `@p` and `@a[distance=..3]` with `StringArgument`?
Since `StringArgument` does not parse these selectors, we think it will be difficult to parse the selectors if we create our own arguments that can parse both.

If you can do it, I would appreciate it if you could tell me exactly how to implement it.

**Comment by book000** [comment]
@broccolai I will reply because there is no response even after about a week and I can not reopen. I'm sorry to get in the way.

 I look forward to your reply.
