### ISSUE TITLE
Exception when using flags and CommandManager.ManagerSettings.LIBERAL_FLAG_PARSING

### ISSUE THREAD

**Issue by TheZexquex** [Incendo/cloud#472]
Hey there,

I have a command that makes use of flags and the option to use a flag everywhere in the command 
(`CommandManager.ManagerSettings.LIBERAL_FLAG_PARSING`)

However, after executing a command that uses this feature for the first time i get that following exception:
```
[23:26:12 INFO]: TheZexquex issued server command: /chain "say hi1" "say hi2" "say hi3" "say hi4"
[23:26:12 INFO]: [Not Secure] [TheZexquex] hi1
[23:26:13 INFO]: [Not Secure] [TheZexquex] hi2
[23:26:13 INFO]: [Not Secure] [TheZexquex] hi3
[23:26:13 INFO]: [Not Secure] [TheZexquex] hi4
[23:26:21 INFO]: TheZexquex issued server command: /chain "say hi1" "say hi2" "say hi3" "say hi4" "say hi5"
[23:26:21 ERROR]: [CommandChain] An unhandled exception was thrown during command execution
java.lang.IllegalStateException: Cannot replace owning command
	at dev.thezexquex.commandchain.libs.cloud.arguments.CommandArgument.setOwningCommand(CommandArgument.java:436) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:357) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.attemptParseUnambiguousChild(CommandTree.java:465) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:192) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parseCommand(CommandTree.java:248) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandTree.parse(CommandTree.java:150) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:116) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.CommandManager.executeCommand(CommandManager.java:189) ~[CommandChain-0.1.0.jar:?]
	at dev.thezexquex.commandchain.libs.cloud.bukkit.BukkitCommand.execute(BukkitCommand.java:116) ~[CommandChain-0.1.0.jar:?]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1003) ~[paper-1.20.1.jar:git-Paper-60]
	at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[paper-1.20.1.jar:git-Paper-60]
	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[paper-1.20.1.jar:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:324) ~[?:?]
	at net.minecraft.commands.Commands.performCommand(Commands.java:308) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2299) ~[?:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$20(ServerGamePacketListenerImpl.java:2259) ~[?:?]
	at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1339) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1316) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1309) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1287) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[paper-1.20.1.jar:git-Paper-60]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-60]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
[23:26:23 INFO]: TheZexquex issued server command: /chain "say hi1" "say hi2" "say hi3" "say hi4" "say hi5"
[23:26:23 INFO]: [Not Secure] [TheZexquex] hi1
[23:26:23 INFO]: [Not Secure] [TheZexquex] hi2
[23:26:23 INFO]: [Not Secure] [TheZexquex] hi3
[23:26:23 INFO]: [Not Secure] [TheZexquex] hi4
[23:26:23 INFO]: [Not Secure] [TheZexquex] hi5
```

Note that it is not mandatory to actually use the flag in the command for the exception to happen.
Furthermore it only happens at the first execution of the command or after adding an additional argument to the command.

Hope you can help me out :D

**Comment by Citymonstret** [comment]
I've tried to replicate using the same command chain and I cannot replicate the issue.  It is likely that we're missing details, but too much has changed since the issue was reported to properly investigate the code using the stacktrace. If this occurs with Cloud v2, then a new issue should be created.
