### ISSUE TITLE
Allow non-alphanumeric command names

### ISSUE THREAD

**Issue by ItsDoot** [Incendo/cloud#622]
When attempting to register the command `/#`, this error is generated: https://github.com/Incendo/cloud/blob/980ba0dfb376496fe58e37da2acb7a59ddfd010f/cloud-core/src/main/java/cloud/commandframework/arguments/CommandArgument.java#L145-L147

Experimentally removing this check doesn't seem to cause any issues on a stock PaperMC 1.20.4 server.

## Code

```java
var manager = PaperCommandManager.createNative(plugin, AsynchronousCommandExecutionCoordinator.<CommandSender>builder().build());
manager.registerBrigadier();
manager.registerAsynchronousCompletions();
// Register exception handlers
new MinecraftExceptionHandler<CommandSender>()
    .withInvalidSyntaxHandler()
    .withInvalidSenderHandler()
    .withNoPermissionHandler()
    .withArgumentParsingHandler()
    .withCommandExecutionHandler()
    .apply(manager, (sender) -> sender);
    
manager.command(
    // line below: at BungerChat-0.1.0-all.jar//town.bunger.chat.plugin.command.Commands.register(Commands.java:44)
    manager.commandBuilder("#", "channels")
        .handler((context) -> {})
);
```

## Stacktrace

```
[03:28:03 WARN]: java.lang.IllegalArgumentException: Name must be alphanumeric
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.CommandArgument.<init>(CommandArgument.java:146)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.CommandArgument.<init>(CommandArgument.java:180)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.CommandArgument.<init>(CommandArgument.java:210)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.CommandArgument.<init>(CommandArgument.java:257)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.CommandArgument.<init>(CommandArgument.java:300)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.StaticArgument.<init>(StaticArgument.java:50)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.arguments.StaticArgument.of(StaticArgument.java:65)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.Command.newBuilder(Command.java:282)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//cloud.commandframework.CommandManager.commandBuilder(CommandManager.java:842)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//town.bunger.chat.plugin.command.Commands.register(Commands.java:44)
[03:28:03 WARN]: 	at BungerChat-0.1.0-all.jar//town.bunger.chat.plugin.BungerChat.onEnable(BungerChat.java:37)
[03:28:03 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[03:28:03 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190)
[03:28:03 WARN]: 	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[03:28:03 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[03:28:03 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637)
[03:28:03 WARN]: 	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548)
[03:28:03 WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673)
[03:28:03 WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433)
[03:28:03 WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[03:28:03 WARN]: 	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1132)
[03:28:03 WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
[03:28:03 WARN]: 	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by Citymonstret** [comment]
We can remove these restrictions and instead do validation when registering with the platforms. We need to ensure that there's no white space in the literals, however.

**Comment by jpenilla** [comment]
This restriction was never carried over into 2.0 in the first place, I've opened a PR adding validation for no whitespace.
