### ISSUE TITLE
CloudBrigadierManager brigadierSourceMapper maybe is null

### ISSUE THREAD

**Issue by bluegreensea** [Incendo/cloud#632]
When I use cloud v2, I got
```
java.lang.NullPointerException: brigadierSourceMapper
	at java.util.Objects.requireNonNull(Objects.java:235) ~[?:?]
	at cloud.commandframework.brigadier.CloudBrigadierManager.<init>(CloudBrigadierManager.java:103) ~[?:?]
	at cloud.commandframework.velocity.VelocityPluginRegistrationHandler.initialize(VelocityPluginRegistrationHandler.java:53) ~[?:?]
	at cloud.commandframework.velocity.VelocityCommandManager.<init>(VelocityCommandManager.java:112) ~[?:?]
	at bluesea.aquautils.AquaUtilsVelocity.onProxyInitialization(AquaUtilsVelocity.kt:85) ~[?:?]
	at bluesea.aquautils.Lmbda$4.execute(Unknown Source) ~[?:?]
	at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-8949e1e8)]
	at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.3.0-SNAPSHOT (git-8949e1e8)]
	at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.3.0-SNAPSHOT (git-8949e1e8)]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:840) [?:?]
```
It seem because some CommandManager set `this.senderMapper = senderMapper;` after initialize.

**Comment by jpenilla** [comment]
https://github.com/Incendo/cloud/commit/9d95fc0c7d1df96ea7a32314ed8babbc4c920085

**Comment by bluegreensea** [comment]
I didn't try, but maybe BukkitCommandManager, BungeeCommandManager, CloudburstCommandManager having this problem too?
