### ISSUE TITLE
Suspending functions with relocated cloud.

### ISSUE THREAD

**Issue by portlek** [Incendo/cloud#716]
Relocated cloud with kotlin coroutines doesn't work.

Also tested with #715 for the parser methods too, still getting the same error but for CommandInput class.

Error:
```
Exception in thread "main" java.lang.RuntimeException: Failed to construct command execution handler
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.constructCommands(AnnotationParser.java:1007)
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.lambda$construct$9(AnnotationParser.java:893)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.construct(AnnotationParser.java:894)
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.parse(AnnotationParser.java:738)
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.parse(AnnotationParser.java:710)
	at org.example.MainKt.main$lambda$0(Main.kt:22)
	at org.example.CLICommandManager$Companion.bootstrap(Main.kt:101)
	at org.example.MainKt.main(Main.kt:19)
// Tries to look at the old package name.
Caused by: java.lang.ClassNotFoundException: org.incendo.cloud.context.CommandContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.parseType(KDeclarationContainerImpl.kt:291)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.loadParameterTypes(KDeclarationContainerImpl.kt:282)
	at kotlin.reflect.jvm.internal.KDeclarationContainerImpl.findMethodBySignature(KDeclarationContainerImpl.kt:215)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:77)
	at kotlin.reflect.jvm.internal.KFunctionImpl$caller$2.invoke(KFunctionImpl.kt:64)
	at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107)
	at kotlin.reflect.jvm.internal.KFunctionImpl.getCaller(KFunctionImpl.kt:64)
	at kotlin.reflect.jvm.ReflectJvmMapping.getJavaMethod(ReflectJvmMapping.kt:64)
	at kotlin.reflect.jvm.ReflectJvmMapping.findKFunction(ReflectJvmMapping.kt:152)
	at kotlin.reflect.jvm.ReflectJvmMapping.getKotlinFunction(ReflectJvmMapping.kt:144)
	at org.example.shade.org.incendo.cloud.kotlin.coroutines.annotations.KotlinAnnotatedMethodsKt.installCoroutineSupport$lambda$0(KotlinAnnotatedMethods.kt:73)
	at org.example.shade.org.incendo.cloud.annotations.AnnotationParser.constructCommands(AnnotationParser.java:997)
	... 14 more
```

Reproduce:
- Create an empty gradle project.
- Add kotlin("jvm") plugin.
- Add shadow jar plugin.
- Add cloud to the project.
- Relocate 'org.incendo.cloud' in shadowJar task.
- Create a command manager and annotation parser.
- Use installCoroutineSupport method to initialize coroutines.
- Parse a command class that has a 'suspend' function.

libs.version.toml
```toml
[versions]
kotlin = "1.9.23"
cloud = "2.0.0-SNAPSHOT"
shadow = "8.1.1"
jansi = "2.4.1"

[libraries]
cloud-core = { module = "org.incendo:cloud-core", version.ref = "cloud" }
cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "cloud" }
cloud-kotlin-extensions = { module = "org.incendo:cloud-kotlin-extensions", version.ref = "cloud" }
cloud-kotlin-coroutines = { module = "org.incendo:cloud-kotlin-coroutines", version.ref = "cloud" }
cloud-kotlin-coroutines-annotations = { module = "org.incendo:cloud-kotlin-coroutines-annotations", version.ref = "cloud" }
jansi = { group = "org.fusesource.jansi", name = "jansi", version.ref = "jansi" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[bundles]
cloud = [
    "jansi",
    "cloud-core",
    "cloud-annotations",
    "cloud-kotlin-extensions",
    "cloud-kotlin-coroutines",
    "cloud-kotlin-coroutines-annotations"
]
```

build.gradle.kts
```kotlin
plugins {
    kotlin("jvm") version libs.versions.kotlin.get()
    alias(libs.plugins.shadow)
}

group = "org.example"

repositories {
    mavenCentral()
    maven("https://oss.sonatype.org/content/repositories/snapshots/")
}

dependencies {
    implementation(libs.bundles.cloud)
}

kotlin {
    jvmToolchain(17)
}

tasks {
    shadowJar {
        mergeServiceFiles()

        manifest {
            attributes["Main-Class"] = "org.example.MainKt"
        }

        relocate("org.incendo.cloud", "org.example.shade.org.incendo.cloud")
    }

    build {
        dependsOn(shadowJar)
    }
}
```

Main.kt
```kotlin
fun main(args: Array<String>) {
    CLICommandManager.bootstrap(args) {
        val annotationParser = AnnotationParser(it, CLISender::class.java)
            .installCoroutineSupport()
        annotationParser.parse(Test())
    }
}

@Command("test")
class Test {

    @Command("")
    suspend fun run(context: CommandContext<CLISender>) {
        println("Hello, World!")
    }
}

// Rest of of the code is from cloud-cli's example.

class CLISender {
    companion object {
        private val INSTANCE: CLISender = CLISender()

        fun sender(): CLISender {
            return INSTANCE
        }
    }
}

fun interface PermissionFunction {
    fun hasPermission(permission: String): Boolean

    companion object {
        fun alwaysTrue(): PermissionFunction = PermissionFunction { true }
    }
}

class CLICommandManager(executionCoordinator: ExecutionCoordinator<CLISender>) :
    CommandManager<CLISender>(
        executionCoordinator,
        CommandRegistrationHandler.nullCommandRegistrationHandler()
    ) {

    private var permissionFunction = PermissionFunction.alwaysTrue()

    init {
        System.setProperty("jansi.graceful", "true")
        JansiLoader.initialize()

        this.registerDefaultExceptionHandlers(
            { triplet ->
                val message: String = triplet.first().formatCaption(triplet.second(), triplet.third())
                System.out.println(ansi().eraseLine().fg(Ansi.Color.RED).a(message).reset())
            },
            { pair ->
                System.err.println(ansi().eraseLine().fg(Ansi.Color.RED).a(pair.first()))
                pair.second().printStackTrace()
                System.err.print(ansi().reset())
            }
        )
    }

    override fun hasPermission(sender: CLISender, permission: String): Boolean {
        return permissionFunction.hasPermission(permission)
    }

    fun permissionFunction(permissionFunction: PermissionFunction) {
        this.permissionFunction = Objects.requireNonNull(permissionFunction)
    }

    fun run(args: Array<String>) {
        Objects.requireNonNull(args, "args")
        try {
            commandExecutor().executeCommand(CLISender.sender(), java.lang.String.join(" ", *args)).join()
        } catch (e: Exception) {
            exitProcess(1)
        }
    }

    companion object {
        fun bootstrap(
            args: Array<String>,
            managerConsumer: Consumer<CLICommandManager>
        ) {
            val cliCommandManager = CLICommandManager(ExecutionCoordinator.simpleCoordinator())
            managerConsumer.accept(cliCommandManager)
            cliCommandManager.run(args)
        }
    }
}
```

**Comment by jpenilla** [comment]
Not a cloud issue.

**Comment by portlek** [comment]
https://github.com/Spliterash/shadow-kotlin-relocate

This Gradle plugin relocates Kotlin's Metadata annotations that solved the reflection problem, in case anyone faces the same issue.
