### ISSUE TITLE
Allow ambiguous nodes

### ISSUE THREAD

**Issue by MelonHell** [Incendo/cloud#780]
Why can't I do this? Using Either is very inconvenient

For example, when using Either, you cannot specify different permissions.
And Either only supports two types, but what if you need more?

```kt
    @Command("tptest <pos>")
    @Permission("command.tptest.pos")
    fun tptestCommand(
        sender: Player,
        pos: Pos,
    ) {
        //
    }

    @Command("tptest <player>")
    @Permission("command.tptest.player")
    fun tptestCommand(
        sender: Player,
        player: Player,
    ) {
        //
    }
```

```
Caused by: org.incendo.cloud.exception.AmbiguousNodeException: Ambiguous Node: player cannot be added as a child to tptest (All children: player, pos)
	at org.incendo.cloud.CommandTree.checkAmbiguity(CommandTree.java:1173)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1116)
	at org.incendo.cloud.CommandTree.checkAmbiguity(CommandTree.java:1204)
	at org.incendo.cloud.CommandTree.verifyAndRegister(CommandTree.java:1063)
	at org.incendo.cloud.CommandTree.insertCommand(CommandTree.java:993)
	at org.incendo.cloud.CommandManager.command(CommandManager.java:244)
	at org.incendo.cloud.annotations.AnnotationParser.parse(AnnotationParser.java:762)
```

Vanilla Minecraft has support for ambiguous nodes and it is very convenient, for example the teleport command
![image](https://github.com/user-attachments/assets/b704b3c5-0be8-4684-a95b-3510f34bd9d4)

**Comment by jpenilla** [comment]
>  And Either only supports two types, but what if you need more?

Then you can write your own parser that disambiguates.

Not supporting ambiguous tree structures is an intentional design decision that we will not be changing.
